// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kprknkbfuqwobpoggkxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtwcmtua2JmdXF3b2Jwb2dna3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNjg5OTYsImV4cCI6MjA1Nzk0NDk5Nn0.EborW7gazpfPI2S-hAhu9f4J6555REcY1cJ1XJiLCW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);